max_num: -1
obj_mass: 0.1   # unit: kg 
miu_coef: [0.6, 0.02]
debug_render: False
debug_viewer: True
debug_dir: ${save_dir}/debug

simulation_metrics: 
  max_pene: 0.005  # If the initial hand penetrates the object too much, regard it as a failure
  max_force: 1.0

arm_pregrasp_is_grasp: True
method: "op" # "op" or "ours"
input_data: "succ_dir" # "grasp_dir" or "succ_dir"

graspdata:
  pregrasp_t: 2 # >0
  squeeze_t: 0 # >0

# evaluation setting
offsets: [0.0] # unit: m; 0.00 or 0.02

# params of our controller
control:
  ablation_name: "default"

  Ke_scalar: 1e5
  stage1_force_thres: 0.2
  tan_motion_pen_weight: 1e3

  free_stage_switch: True
  stage2_after_full_path: True
  desired_sum_force_as_traj: True
  use_desired_sum_force_ub: True

  stage2_incontact_force_only: True
  stage2_penalize_tan_motion: False
  balance_use_normalized: True
  stage2_Ks_hand_only: True

  stage2_tan_force_constraint: False
  stage2_ctrl_tan_force: True

  stage2_increase_force: False
  stage2_equal_joint_force_cost: True
  
  use_multi_contact_model: True
  stage2_penalize_contact_qda: True
  jaco_reference_frame: True


