# xml_path: third_party/mujoco_menagerie/leap_hand/right_hand.xml
xml_path: assets/hand/leap_tac3d/leap_tac3d.xml
mocap: True
exclude_table_contact: 
color: [0.132868, 0.496933, 0.144129, 1.0]
finger_prefix: 
valid_body_name: 
tip_body_name: 